title: Jason Pondugula 
#logo: /filepath to image - circularimage.png of headshot
Technical Skills: Python, SQL, AWS, C, HTML, CSS
Connect with Me on LinkedIn! - https://www.linkedin.com/in/jason-pondugula/
#show_downloads: true (ppl can download or see code) 
theme: jekyll-theme-minimal
