title: Jason Pondugula 
logo: /assets/img/ValedictorianPic.jpeg
# Technical Skills Section
description: >
  Technical Skills: Python, SQL, AWS, C, HTML, CSS

# Personal Description Section
description: >
  I am a passionate software developer with an interest in AI, machine learning, and Cloud Computing. 
  With a strong foundation in computer science principles and a commitment to lifelong 
  learning, I constantly seek to improve my skills and apply them in innovative ways.

linkedin_url: "https://www.linkedin.com/in/jason-pondugula/"
#show_downloads: true (ppl can download or see code) 
theme: jekyll-theme-minimal
